FROM ubuntu
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get install -y python3
RUN apt-get install -y pip
RUN apt-get install -y dnsutils
RUN apt-get install -y iputils-ping
RUN apt-get install -y netcat
RUN apt-get install -y traceroute
RUN apt-get install -y net-tools
RUN apt-get install -y wget
RUN apt-get install -y sysstat